<a href="https://colab.research.google.com/github/NallabothulaSaiSruthi/6thSem-ML-lab/blob/main/Lab_1_ML_DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from scipy import stats

In [ ]:
from  google.colab import files
uploaded=files.upload()

Saving Dataset of Diabetes .csv to Dataset of Diabetes .csv

In [ ]:
df=pd.read_csv('Dataset of Diabetes .csv')
df.head(10)

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
5,634,34224,F,45,2.3,24,4.0,2.9,1.0,1.0,1.5,0.4,21.0,N
6,721,34225,F,50,2.0,50,4.0,3.6,1.3,0.9,2.1,0.6,24.0,N
7,421,34227,M,48,4.7,47,4.0,2.9,0.8,0.9,1.6,0.4,24.0,N
8,670,34229,M,43,2.6,67,4.0,3.8,0.9,2.4,3.7,1.0,21.0,N
9,759,34230,F,32,3.6,28,4.0,3.8,2.0,2.4,3.8,1.0,24.0,N

In [ ]:
df1=df.isnull().sum()
df1

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [ ]:
df2=df.describe()
df2

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB
None

In [ ]:
df.loc[5,'AGE']=np.nan
df.loc[7,'BMI']=np.nan
df.loc[8,'HDL']=np.nan
df.loc[6,'Chol']=np.nan
df.head(10)

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50.0,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26.0,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50.0,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50.0,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33.0,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
5,634,34224,F,NaN,2.3,24,4.0,2.9,1.0,1.0,1.5,0.4,21.0,N
6,721,34225,F,50.0,2.0,50,4.0,NaN,1.3,0.9,2.1,0.6,24.0,N
7,421,34227,M,48.0,4.7,47,4.0,2.9,0.8,0.9,1.6,0.4,NaN,N
8,670,34229,M,43.0,2.6,67,4.0,3.8,0.9,NaN,3.7,1.0,21.0,N
9,759,34230,F,32.0,3.6,28,4.0,3.8,2.0,2.4,3.8,1.0,24.0,N

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        999 non-null    float64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       999 non-null    float64
 8   TG         1000 non-null   float64
 9   HDL        999 non-null    float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        999 non-null    float64
 13  CLASS      1000 non-null   object
dtypes: float64(9), int64(3), object(2)
memory usage: 109.5+ KB
None

In [ ]:
print(df.describe())

                ID     No_Pation         AGE         Urea           Cr  \
count  1000.000000  1.000000e+03  999.000000  1000.000000  1000.000000
mean    340.500000  2.705514e+05   53.536537     5.124743    68.943000
std     240.397673  3.380758e+06    8.799504     2.935165    59.984747
min       1.000000  1.230000e+02   20.000000     0.500000     6.000000
25%     125.750000  2.406375e+04   51.000000     3.700000    48.000000
50%     300.500000  3.439550e+04   55.000000     4.600000    60.000000
75%     550.250000  4.538425e+04   59.000000     5.700000    73.000000
max     800.000000  7.543566e+07   79.000000    38.900000   800.000000

             HbA1c        Chol           TG         HDL          LDL  \
count  1000.000000  999.000000  1000.000000  999.000000  1000.000000
mean      8.281160    4.864084     2.349610    1.203554     2.609790
std       2.534003    1.301775     1.401176    0.659659     1.115102
min       0.900000    0.000000     0.300000    0.200000     0.300000
25%       6.500000    4.000000     1.500000    0.900000     1.800000
50%       8.000000    4.800000     2.000000    1.100000     2.500000
75%      10.200000    5.600000     2.900000    1.300000     3.300000
max      16.000000   10.300000    13.800000    9.900000     9.900000

              VLDL         BMI
count  1000.000000  999.000000
mean      1.854700   29.583604
std       3.663599    4.961730
min       0.100000   19.000000
25%       0.700000   26.000000
50%       0.900000   30.000000
75%       1.500000   33.000000
max      35.000000   47.750000

In [ ]:
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

AGE     1
Chol    1
HDL     1
BMI     1
dtype: int64

In [ ]:
df3=df['BMI'].isnull()
print(df[df3])

    ID  No_Pation Gender   AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
7  421      34227      M  48.0   4.7  47    4.0   2.9  0.8  0.9  1.6   0.4

   BMI CLASS
7  NaN     N

In [ ]:
#Set the values to some value (zero, the mean, the median, etc.).
# Step 1: Create an instance of SimpleImputer with the median strategy for Age and mean stratergy for Salary
imputer1 = SimpleImputer(strategy="median")
imputer2 = SimpleImputer(strategy="mean")
imputer3 = SimpleImputer(strategy="median")
imputer4 = SimpleImputer(strategy="mean")

df_copy=df

# Step 2: Fit the imputer on the "Age" and "Salary"column
# Note: SimpleImputer expects a 2D array, so we reshape the column
imputer1.fit(df_copy[["AGE"]])
imputer2.fit(df_copy[["Chol"]])
imputer3.fit(df_copy[["HDL"]])
imputer4.fit(df_copy[["BMI"]])

# Step 3: Transform (fill) the missing values in the "Age" and "Salary"c column
df_copy["AGE"] = imputer1.transform(df[["AGE"]])
df_copy["Chol"] = imputer2.transform(df[["Chol"]])
df_copy["HDL"] = imputer3.transform(df[["HDL"]])
df_copy["BMI"] = imputer4.transform(df[["BMI"]])

# Verify that there are no missing values left
print(df_copy["AGE"].isnull().sum())
print(df_copy["Chol"].isnull().sum())
print(df_copy["HDL"].isnull().sum())
print(df_copy["BMI"].isnull().sum())

0
0
0
0

In [ ]:
#Handling Categorical Attributes
#Using Ordinal Encoding for gender COlumn and One-Hot Encoding for City Column

# Initialize OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=[["F", "M"]])
df_copy['Gender']=df_copy['Gender'].str.upper()
# Fit and transform the data
df_copy["Gender_Encoded"] = ordinal_encoder.fit_transform(df_copy[["Gender"]])

# Initialize OneHotEncoder
onehot_encoder = OneHotEncoder()

# Fit and transform the "City" column
encoded_data = onehot_encoder.fit_transform(df[["CLASS"]])

# Convert the sparse matrix to a dense array
encoded_array = encoded_data.toarray()

# Convert to DataFrame for better visualization
encoded_df = pd.DataFrame(encoded_array, columns=onehot_encoder.get_feature_names_out(["CLASS"]))
df_encoded = pd.concat([df_copy, encoded_df], axis=1)

df_encoded.drop("Gender", axis=1, inplace=True)
df_encoded.drop("CLASS", axis=1, inplace=True)

print(df_encoded. head())

    ID  No_Pation   AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  \
0  502      17975  50.0   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1  735      34221  26.0   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2  420      47975  50.0   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3  680      87656  50.0   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4  504      34223  33.0   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0

   Gender_Encoded  CLASS_N  CLASS_N   CLASS_P  CLASS_Y  CLASS_Y
0             0.0      1.0       0.0      0.0      0.0       0.0
1             1.0      1.0       0.0      0.0      0.0       0.0
2             0.0      1.0       0.0      0.0      0.0       0.0
3             0.0      1.0       0.0      0.0      0.0       0.0
4             1.0      1.0       0.0      0.0      0.0       0.0

In [ ]:
#Data Transformation
# Min-Max Scaler/Normalization (range 0-1)
#Pros: Keeps all data between 0 and 1; ideal for distance-based models.
#Cons: Can distort data distribution, especially with extreme outliers.
normalizer = MinMaxScaler()
df_encoded[['BMI']] = normalizer.fit_transform(df_encoded[['BMI']])
df_encoded.head()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_Encoded,CLASS_N,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,502,17975,50.0,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,0.173913,0.0,1.0,0.0,0.0,0.0,0.0
1,735,34221,26.0,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,0.139130,1.0,1.0,0.0,0.0,0.0,0.0
2,420,47975,50.0,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,0.173913,0.0,1.0,0.0,0.0,0.0,0.0
3,680,87656,50.0,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,0.173913,0.0,1.0,0.0,0.0,0.0,0.0
4,504,34223,33.0,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,0.069565,1.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
# Standardization (mean=0, variance=1)
#Pros: Works well for normally distributed data; suitable for many models.
#Cons: Sensitive to outliers.
scaler = StandardScaler()
df_encoded[['AGE']] = scaler.fit_transform(df_encoded[['AGE']])
df_encoded.head()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_Encoded,CLASS_N,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,502,17975,-0.402465,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,0.173913,0.0,1.0,0.0,0.0,0.0,0.0
1,735,34221,-3.132585,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,0.139130,1.0,1.0,0.0,0.0,0.0,0.0
2,420,47975,-0.402465,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,0.173913,0.0,1.0,0.0,0.0,0.0,0.0
3,680,87656,-0.402465,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,0.173913,0.0,1.0,0.0,0.0,0.0,0.0
4,504,34223,-2.336300,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,0.069565,1.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
from  google.colab import files
uploaded=files.upload()

Saving adult.csv.zip to adult.csv.zip

In [ ]:
from  google.colab import files
uploaded=files.upload()

Saving adult.csv to adult.csv

In [ ]:
df4=pd.read_csv('adult.csv')
df4.head(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States,<=50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,<=50K

In [ ]:
df4.loc[5,'age']=np.nan
df4.loc[7,'education']=np.nan
df4.loc[8,'relationship']=np.nan
df4.loc[6,'gender']=np.nan
df4.head(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25.0,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38.0,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28.0,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44.0,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18.0,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
5,NaN,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
6,29.0,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,NaN,0,0,40,United-States,<=50K
7,63.0,Self-emp-not-inc,104626,NaN,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
8,24.0,Private,369667,Some-college,10,Never-married,Other-service,NaN,White,Female,0,0,40,United-States,<=50K
9,55.0,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,<=50K

In [ ]:
print(df4.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48841 non-null  float64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48841 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48841 non-null  object
 8   race             48842 non-null  object
 9   gender           48841 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: float64(1), int64(5), object(9)
memory usage: 5.6+ MB
None

In [ ]:
print(df4.describe())

                age        fnlwgt  educational-num  capital-gain  \
count  48841.000000  4.884200e+04     48842.000000  48842.000000
mean      38.643681  1.896641e+05        10.078089   1079.067626
std       13.710634  1.056040e+05         2.570973   7452.019058
min       17.000000  1.228500e+04         1.000000      0.000000
25%       28.000000  1.175505e+05         9.000000      0.000000
50%       37.000000  1.781445e+05        10.000000      0.000000
75%       48.000000  2.376420e+05        12.000000      0.000000
max       90.000000  1.490400e+06        16.000000  99999.000000

       capital-loss  hours-per-week
count  48842.000000    48842.000000
mean      87.502314       40.422382
std      403.004552       12.391444
min        0.000000        1.000000
25%        0.000000       40.000000
50%        0.000000       40.000000
75%        0.000000       45.000000
max     4356.000000       99.000000

In [ ]:
missing_values2 = df4.isnull().sum()
print(missing_values2[missing_values2 > 0])

age             1
education       1
relationship    1
gender          1
dtype: int64

In [ ]:
#Set the values to some value (zero, the mean, the median, etc.).
# Step 1: Create an instance of SimpleImputer with the median strategy for Age and mean stratergy for Salary
imputer1 = SimpleImputer(strategy="median")
imputer2 = SimpleImputer(strategy="mean")
imputer3 = SimpleImputer(strategy="median")
imputer4 = SimpleImputer(strategy="median")

df_copy2=df4

# Step 2: Fit the imputer on the "Age" and "Salary"column
# Note: SimpleImputer expects a 2D array, so we reshape the column
imputer1.fit(df_copy2[["age"]])
imputer2.fit(df_copy2[["educational-num"]])
imputer3.fit(df_copy2[["capital-gain"]])
imputer4.fit(df_copy2[["hours-per-week"]])

# Step 3: Transform (fill) the missing values in the "Age" and "Salary"c column
df_copy2["age"] = imputer1.transform(df4[["age"]])
df_copy2["educational-num"] = imputer2.transform(df4[["educational-num"]])
df_copy2["capital-gain"] = imputer3.transform(df4[["capital-gain"]])
df_copy2["hours-per-week"] = imputer4.transform(df4[["hours-per-week"]])

# Verify that there are no missing values left
print(df_copy2["age"].isnull().sum())
print(df_copy2["educational-num"].isnull().sum())
print(df_copy2["capital-gain"].isnull().sum())
print(df_copy2["hours-per-week"].isnull().sum())

0
0
0
0